resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/MuneebBaderoen/flight-school
    branch: docker

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml